### ISSUE TITLE
The TMP1x2 Alert Pin, Interrupt Pin undefined

### ISSUE THREAD

**Issue by smittytone** [electricimp/TMP1x2#2]
The Read Me refers to Altert and Interrupt pins for comparator and interrupt modes. These are not set in the constructor. We should think about doing so, and at the very least include a wiring diagram in the Read Me so folks know they may want to connect up other imp pins to the device - and how to configure those pins.

**Comment by ersatzavian** [comment]
We deliberately did not include these inside the class. Interested to hear what you think when you hear why:

The class includes methods to set up the interrupt/alert pin to work however you'd like. Including the pin in the class isn't required to do this. If the pin is included in the class, then the class must reconfigure the pin in order to assign its own state-change callback, just to redirect that event to the class consumer's alert or interrupt callback. So instead, we allow you to easily set up the device for the interrupt/alert mode you want, and leave it to the class consumer to configure and use that pin as they would like. 

This has come up twice this week (once with you, once with Betsy), so maybe this is worth a bit more documentation in the README at least.

Thoughts?

**Comment by smittytone** [comment]
That makes sense. We just need to say that in the Read Me so that folks don't get down to the references to those pins and wonder what they are, as I did. I'm working on migrating library docs to the Dev Center, so I'll work on it there and get you to have a look at it to make sure I’ve understood it correctly.

**Comment by ersatzavian** [comment]
Ok, this is open now as a story in Pivotal, so let's close this one here.

**Comment by cat-haines** [comment]
We're going to leave both open - I'm trying to set us up to be transparent about work we do on public libraries, etc :smiley:
